### ISSUE TITLE
top directory should be named commerce_ubc_cbm

### ISSUE THREAD

**Issue by robbdavis** [ubc-web-services/d7-commerce-ubc-cbm#1]
Not sure how to make it happen in git but currently on download, the module is unpacked with the incorrect directory name.

**Comment by carlinubc** [comment]
Yes it would be nice to have the same name as the module

**Comment by gocaps** [comment]
I believe this would require changing the project name on Github. Since the .git directory is inside the incorrectly named folder, you can change the name of that folder locally and not have any issues.

**Comment by gocaps** [comment]
Closing as "will not fix"

**Comment by joelpittet** [comment]
Any reason why the project name couldn't be changed?  D7 could be a branch/tag if you plan to port it.
