### ISSUE TITLE
Not having a readme.txt file throws and error.

### ISSUE THREAD

**Issue by robbdavis** [ubc-web-services/d7-commerce-ubc-cbm#2]
Warning: file_get_contents(sites/webforms.students.ubc.ca/modules/commerce_ubc_cbm/README.txt): failed to open stream: No such file or directory in commerce_ubc_cbm_help() (line 118 of /www_data/aegir/platforms/drupal-7.38/sites/webforms.students.ubc.ca/modules/commerce_ubc_cbm/commerce_ubc_cbm.module).

changing readme.md to readme.txt fixes this error.

**Comment by carlinubc** [comment]
I've created a pull request for this error. #3

**Comment by gocaps** [comment]
Pull request was accepted (as a Squash, due to trivial change). Thanks @carlinubc !
