### ISSUE TITLE
Out of date code?

### ISSUE THREAD

**Issue by joelpittet** [ubc-web-services/d7-commerce-ubc-cbm#6]
I'm working with a project that looks to have maybe newer code than this.
It has a line in the module file that says

> Updated July 2015 UBC IT Web Services, Sean

Is this code maybe still not the one to use in production, do you have another repo or should I maybe post that code here for you to review if you don't know 'Sean' from Web Services?

Thank you

**Comment by ficklecat** [comment]
Funny I was just browsing this at the same time and saw your comment. Yeah that's me (tall guy from DrupalCon). The code you have is probably from the develop branch. I did not merge back in to master yet though it has been working live for some time now.

**Comment by joelpittet** [comment]
Oh hey Sean!  you are that sean. I didn't see the Develop branch either.  Are you planning on merging that to master?  Mind if I send a pull request?

**Comment by joelpittet** [comment]
Is there any chance we can remove the `field_collection` dependency?

**Comment by ficklecat** [comment]
Hi Joel, yes I am planning on merging it in. I will look into it on Monday.

I think if I remove the field_collection dependency it will fail to install as it tries to create a field of that type to hold the credentials. See commerce_ubc_cbm_add_field_collection_fields() although perhaps this can be made optional.

**Comment by ficklecat** [comment]
OK yeah and a pull request is fine.

**Comment by joelpittet** [comment]
Trying to wrap my head around why those field collection fields are needed?  Do you know why?  The field is hidden widget so I don't see how people can use it in a practical sense, or maybe I'm missing something.

**Comment by ficklecat** [comment]
Hey Joel, our use case is that we needed merchant credentials and different GL codes at the product and taxonomy level (not just a single set of credentials on the payment processor). I created a field collection to group the required fields together and to make it easier to attach. It is used when you edit a product/taxonomy, hidden when you view it as a user. I think this extra complexity was why I did not merge into master as some people do not need this so perhaps it would be better keeping as a separate branch?

**Comment by joelpittet** [comment]
Maybe a sub module even?  It's nice to keep the develop branch as the latest code and master as the latest stable but with a feature in develop that you may not want to merge it probably should be split out as you said another branch or as a sub-module.

I've got a pull request for whitespace cleanup at #7. Trying to just make things consistent so it's easier to see the changes after (I hope)

**Comment by ficklecat** [comment]
Not too familiar with sub modules so how about I just rename this branch, then we can create a new develop branch based on master and then fix that one up?

**Comment by joelpittet** [comment]
That sounds good to me too

**Comment by joelpittet** [comment]
https://github.com/ubc-web-services/d7-commerce-ubc-cbm/pull/8  Created the same whitespace kind of issue for the master branch.

**Comment by ficklecat** [comment]
Hey @joelpittet I finally managed to work on this some more (in develop branch) and added the variables to the payment settings form and got rid of all those constants and some other cleanup. Needs more testing but it shouldn't be far off. Any comments let me know!
